name = "moonshotai-kimi-k2-6"
attachment = true
reasoning = true
tool_call = true
structured_output = true
release_date = "2026-05-07"
last_updated = "2026-05-07"
open_weights = true

[cost]
input = 0.6
output = 3.05
cache_read = 0.13

[limit]
context = 262144
input = 262144
output = 49152

[modalities]
input = ["text", "image"]
output = ["text"]
