name = "GPT-5 Mini"
attachment = true
reasoning = true
tool_call = true
structured_output = true
release_date = "2026-06-24"
last_updated = "2026-06-24"
open_weights = false

[cost]
input = 0.25
output = 2.0
cache_read = 0.025

[limit]
context = 131072
input = 131072
output = 128000

[modalities]
input = ["text", "image"]
output = ["text"]
