name = "GLM-4.7"
attachment = false
reasoning = true
tool_call = true
structured_output = true
release_date = "2026-03-12"
last_updated = "2026-03-12"
open_weights = true

[cost]
input = 0.34
output = 1.487
cache_read = 0.04

[limit]
context = 200000
input = 200000
output = 131072

[modalities]
input = ["text"]
output = ["text"]
